Author: Alan
Project: A rocketchip demo
Genome:
   Name: fake_genome
   Location: /home/azhang/rocketchip/demo/01_raw_data/genome.fa
Reads:
   Samples:
      grp1: [exp_a, exp_b]
      grp2: [exp_c]
   Controls:
      ctl1: [input]
Readtype: paired
Peaktype: narrow
Aligner: bwa_mem
Deduplicator: samtools
Peakcaller: macs3
Threads: 1
